name: On Push To Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"


jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: kiloexabyte/runner-image
    steps:
      - name: Expose cache vars
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL']);
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN']);
      - uses: actions/checkout@v6
      - name: Run Go script
        env: 
          GOFLAGS: -buildvcs=false
          ACTIONS_CACHE_URL: ${{ env.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
        run: |
          op lint
          op test
          op build
